export const accountingGroupsMock = {
  id: "mock-acc",
  name: "Mock accounting",
  year: 2022,
  groupType: "expense",
  groups: [
    {
      id: "casa",
      name: "Casa",
      categories: [
        {
          id: "cat1",
          name: "Alquiler",
          annualTotals: {
            monthly: [
              { id: 1, ammount: 11 },
              { id: 2, ammount: 12 },
              { id: 3, ammount: 13 },
              { id: 4, ammount: 14 },
              { id: 5, ammount: 15 },
              { id: 6, ammount: 0 },
              { id: 7, ammount: 10 },
              { id: 8, ammount: 10 },
              { id: 9, ammount: 7 },
              { id: 10, ammount: 10 },
              { id: 11, ammount: 10 },
              { id: 12, ammount: 10 },
            ],
            total: 23,
            average: 32,
          },
        },
        {
          id: "cat2",
          name: "Luz",
          annualTotals: {
            monthly: [
              { id: 1, ammount: 11 },
              { id: 2, ammount: 12 },
              { id: 3, ammount: 13 },
              { id: 4, ammount: 14 },
              { id: 5, ammount: 15 },
              { id: 6, ammount: 0 },
              { id: 7, ammount: 10 },
              { id: 8, ammount: 10 },
              { id: 9, ammount: 7 },
              { id: 10, ammount: 10 },
              { id: 11, ammount: 10 },
              { id: 12, ammount: 10 },
            ],
            total: 23,
            average: 32,
          },
        },
        {
          id: "cat3",
          name: "Gas",
          annualTotals: {
            monthly: [
              { id: 1, ammount: 11 },
              { id: 2, ammount: 12 },
              { id: 3, ammount: 13 },
              { id: 4, ammount: 14 },
              { id: 5, ammount: 15 },
              { id: 6, ammount: 0 },
              { id: 7, ammount: 10 },
              { id: 8, ammount: 10 },
              { id: 9, ammount: 7 },
              { id: 10, ammount: 10 },
              { id: 11, ammount: 10 },
              { id: 12, ammount: 10 },
            ],
            total: 23,
            average: 32,
          },
        },
      ],
    },
    {
      id: "coche",
      name: "Coche",
      categories: [
        {
          id: "cat4",
          name: "Seguro",
          annualTotals: {
            monthly: [
              { id: 1, ammount: 11 },
              { id: 2, ammount: 12 },
              { id: 3, ammount: 13 },
              { id: 4, ammount: 14 },
              { id: 5, ammount: 15 },
              { id: 6, ammount: 0 },
              { id: 7, ammount: 10 },
              { id: 8, ammount: 10 },
              { id: 9, ammount: 7 },
              { id: 10, ammount: 10 },
              { id: 11, ammount: 10 },
              { id: 12, ammount: 10 },
            ],
            total: 23,
            average: 32,
          },
        },
        {
          id: "cat5",
          name: "Gasolina",
          annualTotals: {
            monthly: [
              { id: 1, ammount: 11 },
              { id: 2, ammount: 12 },
              { id: 3, ammount: 13 },
              { id: 4, ammount: 14 },
              { id: 5, ammount: 15 },
              { id: 6, ammount: 0 },
              { id: 7, ammount: 10 },
              { id: 8, ammount: 10 },
              { id: 9, ammount: 7 },
              { id: 10, ammount: 10 },
              { id: 11, ammount: 10 },
              { id: 12, ammount: 10 },
            ],
            total: 23,
            average: 32,
          },
        },
      ],
    },
  ],
};
