export const accountingMock = {
  id: "mock",
  name: "Mock accounting",
  year: 2022,
  income: {
    groups: [
      {
        id: "salario",
        name: "Salario",
        annualTotals: {
          monthly: [
            { id: 1, ammount: 10 },
            { id: 2, ammount: 10 },
            { id: 3, ammount: 10 },
            { id: 4, ammount: 10 },
            { id: 5, ammount: 10 },
            { id: 6, ammount: 0 },
            { id: 7, ammount: 10 },
            { id: 8, ammount: 10 },
            { id: 9, ammount: 7 },
            { id: 10, ammount: 10 },
            { id: 11, ammount: 10 },
            { id: 12, ammount: 10 },
          ],
          total: 23,
          average: 32,
        },
      },
    ],
  },
  expenses: {
    groups: [
      {
        id: "casa",
        name: "Casa",
        annualTotals: {
          monthly: [
            { id: 1, ammount: 10 },
            { id: 2, ammount: 10 },
            { id: 3, ammount: 10 },
            { id: 4, ammount: 10 },
            { id: 5, ammount: 10 },
            { id: 6, ammount: 0 },
            { id: 7, ammount: 10 },
            { id: 8, ammount: 10 },
            { id: 9, ammount: 7 },
            { id: 10, ammount: 10 },
            { id: 11, ammount: 10 },
            { id: 12, ammount: 10 },
          ],
          total: 23,
          average: 32,
        },
      },
      {
        id: "coche",
        name: "Coche",
        annualTotals: {
          monthly: [
            { id: 1, ammount: 10 },
            { id: 2, ammount: 10 },
            { id: 3, ammount: 10 },
            { id: 4, ammount: 10 },
            { id: 5, ammount: 10 },
            { id: 6, ammount: 0 },
            { id: 7, ammount: 10 },
            { id: 8, ammount: 10 },
            { id: 9, ammount: 7 },
            { id: 10, ammount: 10 },
            { id: 11, ammount: 10 },
            { id: 12, ammount: 10 },
          ],
          total: 23,
          average: 32,
        },
      },
    ],
  },
  totals: {
    income: {
      monthly: [
        { id: 1, ammount: 11 },
        { id: 2, ammount: 12 },
        { id: 3, ammount: 13 },
        { id: 4, ammount: 14 },
        { id: 5, ammount: 15 },
        { id: 6, ammount: 0 },
        { id: 7, ammount: 10 },
        { id: 8, ammount: 10 },
        { id: 9, ammount: 7 },
        { id: 10, ammount: 10 },
        { id: 11, ammount: 10 },
        { id: 12, ammount: 10 },
      ],
      total: 23,
      average: 32,
    },
    expenses: {
      monthly: [
        { id: 1, ammount: 10 },
        { id: 2, ammount: 10 },
        { id: 3, ammount: 10 },
        { id: 4, ammount: 10 },
        { id: 5, ammount: 10 },
        { id: 6, ammount: 10 },
        { id: 7, ammount: 10 },
        { id: 8, ammount: 10 },
        { id: 9, ammount: 10 },
        { id: 10, ammount: 10 },
        { id: 11, ammount: 10 },
        { id: 12, ammount: 10 },
      ],
      total: 23,
      average: 32,
    },
    savings: {
      monthly: [
        { id: 1, ammount: 10 },
        { id: 2, ammount: 10 },
        { id: 3, ammount: 10 },
        { id: 4, ammount: 10 },
        { id: 5, ammount: 10 },
        { id: 6, ammount: 10 },
        { id: 7, ammount: 10 },
        { id: 8, ammount: 10 },
        { id: 9, ammount: 10 },
        { id: 10, ammount: 10 },
        { id: 11, ammount: 10 },
        { id: 12, ammount: 10 },
      ],
      total: 23,
      average: 32,
    },
  },
};
